version: '3'

services:
    php-apache:
        container_name: phptest-php-apache
        build: .
        volumes:
            - ./php_test_app/:/var/www/html
        ports:
            - 8000:80
        depends_on:
            - db
        links:
            - db

    db:
        container_name: phptest-db
        image: mysql
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root+
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: testdb

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        environment:
#            - PMA_ARBITRARY=1
#        restart: always
#        ports:
#            - 8080:80
#        volumes:
#            - /sessions
#        depends_on:
#            - db
#        links:
#            - db
